import initTabNav from "./modules/initTabNav.js";
import initAccordion from "./modules/initAccordion.js";
import initScrollSuave from "./modules/initScrollSuave.js";
import initAnimacaoScroll from "./modules/initAnimacaoScroll.js";
import initModal from "./modules/modal.js";
import initToolTip from "./modules/initTooltip.js";
import initDropdownMenu from "./modules/initDropdownMenu.js";
import initMenuMobile from "./modules/initMenuMobile.js";
import initFuncionamento from "./modules/initFuncionamento.js";
import initFetchAnimais from "./modules/fetchAnimais.js";
import initFetchBitcoin from "./modules/fetchBitcoin.js";

initTabNav();
initAccordion();
initScrollSuave();
initAnimacaoScroll();
initModal();
initToolTip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
